### ISSUE TITLE
nacl-did dependency missing

### ISSUE THREAD

**Issue by simonas-notcat** [uport-project/did-jwt#33]
After upgrading to the latest version, I'm getting this error:

```
error: bundling failed: Error: Unable to resolve module `nacl-did`
 from `.../uport-mobile/node_modules/did-jwt/lib/NaclSigner.js`: 
Module `nacl-did` does not exist in the Haste module map
```

It is being used explicitly: 
https://github.com/uport-project/did-jwt/blob/develop/src/NaclSigner.js#L3

But it was removed from dependency list on purpose? :

https://github.com/uport-project/did-jwt/commit/37a57409de8a5f4175a26dead35b547cdd4617cd#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R44

**Comment by oed** [comment]
Seems quite redundant to import `nacl-did` for only this line of code: https://github.com/uport-project/nacl-did/blob/develop/src/register.ts#L86

**Comment by mi-xu** [comment]
Should be fixed by https://github.com/uport-project/did-jwt/pull/34
Available on npm now as [v0.1.3-alpha.1](https://www.npmjs.com/package/did-jwt/v/0.1.3-alpha.1)

**Comment by oed** [comment]
Nice @mi-xu 🙌

**Comment by oed** [comment]
@mi-xu this issue is still present. Seems like you forgot to build before you did the release. It's usually good to add an autobuild script when you run npm publish 🙂

**Comment by mi-xu** [comment]
@oed Can you try the release version? https://www.npmjs.com/package/did-jwt/v/0.1.3

**Comment by oed** [comment]
Sorry my bad! Should had double checked, thought I did update to 0.1.3, but was on 0.1.2.

**Comment by mi-xu** [comment]
@oed No worries! Closing this issue now that it seems to be working.
